GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/<your_id>

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Charlie Brown",
  "subscribedChannel": "Snoopy Channel"
}

###

PATCH http://localhost:3000/subscribers/<your_id>
Content-Type: application/json 

{
  "name": "Tommy"
}

###

DELETE http://localhost:3000/subscribers/<your_id>
